In [7]:
from ucimlrepo import fetch_ucirepo 
import numpy as np
import pandas as pd

In [10]:
X_train = [[9.397, 21.68, 59.75, 268.8, 0.07969], [27.42, 26.27, 186.9, 2501.0, 0.1084], [13.68, 16.33, 87.76, 575.5, 0.09277], [13.68, 16.33, 87.76, 575.5, 0.09277], [13.68, 16.33, 87.76, 575.5, 0.09277], [13.68, 16.33, 87.76, 575.5, 0.09277], [13.68, 16.33, 87.76, 575.5, 0.09277], [13.68, 16.33, 87.76, 575.5, 0.09277], [13.68, 16.33, 87.76, 575.5, 0.09277]]
y_train = [1, 0, 1, 1, 1, 1, 1, 1, 1]
x = [[14.19, 23.81, 92.87, 610.7, 0.09463]]

X_train = np.array(X_train)
y_train = np.array(y_train)
x = np.array(x)

In [11]:
distances = np.sum(np.power(X_train - x, 2), axis=1)
distances

array([1.18020054e+05, 3.58225682e+06, 1.32136260e+03, 1.32136260e+03,
       1.32136260e+03, 1.32136260e+03, 1.32136260e+03, 1.32136260e+03,
       1.32136260e+03])

In [13]:
k_indices = np.argsort(distances)[:3]
k_indices

array([2, 3, 4], dtype=int64)

In [14]:
k_nearest_labels = y_train[k_indices]
k_nearest_labels

array([1, 1, 1])

In [17]:
np.bincount(k_nearest_labels)

array([0, 3], dtype=int64)

In [18]:
np.argmax(np.bincount(k_nearest_labels))

1